### PR TITLE
fix navigation bar sign-in check, change AppBar position

### LINKED ISSUE #73: fix navigation bar position when scrolling down
change AppBar position props to sticky

### LINKED ISSUE #74: fix problem of checking sign in status
me queries are sent regardless of Cookie existence, needs to be fixed

### PR DESCRIPTION
**Pull request by mskwon1**
resolves #73 
resolves #74

### CODE REVIEW

File: web/src/components/signup-form-google.js [hunk 1]
```diff
@@ -14,18 +14,21 @@ class SignupFormGoogle extends Component {
...
       lastName: '',
       email: '',
+      profileImgUrl: '',
       // TODO(Myoung-heeSeo) : this will be used when facebook login is added.
       provider: '',
     };
   }
 
   responseGoogle = res => {
+    console.log(res);
```
Comment (YoonYeoHwan) [inline web/src/components/signup-form-google.js]: remove it

File: web/src/components/navigation/navbar.js [hunk 2]
```diff
@@ -1,44 +1,69 @@
...
+  me {
+    profileImgUrl
+  }
+}
+`;
+
+function Navbar(props) {
+  if (isWidthUp('md', props.width)) {
+    // When there is token, send me query to get profile pic.
+    if (Cookies.get('token')) {
```
Comment (ethkim) [inline web/src/components/navigation/navbar.js]: This logic is duplicated below. Can we try to merge them and use an if block to decide whether to return NavBarPC vs NavBarMobile?
